### Using: @ext:rest REST Client VSCode extension
@apphost = {{$dotenv APP_HOST}}
@appport = {{$dotenv APP_PORT}}

### DEBUG
GET http://{{apphost}}:{{appport}}/api/edit

### Add quiz
// @name addQuiz
POST http://{{apphost}}:{{appport}}/api/edit/quiz
Content-Type: application/json

{
  "title": "Quiz 2",
  "questions": 5
}

###

@quiz_id = {{addQuiz.response.body.lastID}}

### Update quiz
PUT http://{{apphost}}:{{appport}}/api/edit/quiz/{{quiz_id}}
Content-Type: application/json

{
  "title": "Quiz 1 v2",
  "questions": 9
}

### Publish quiz
PUT http://{{apphost}}:{{appport}}/api/edit/quiz/publish/{{quiz_id}}

### Add question
// @name addQuestion
POST http://{{apphost}}:{{appport}}/api/edit/quiz/{{quiz_id}}/question
Content-Type: application/json

{
  "question": "Question 1",
  "choices": 5,
  // type: Refer to question_type table in database
  "type": 1
}

###

@question_id = {{addQuestion.response.body.lastID}}

### Update question
PUT http://{{apphost}}:{{appport}}/api/edit/quiz/{{quiz_id}}/question/{{question_id}}
Content-Type: application/json

{
  "question": "Question 1 v2",
  "choices": 4,
  // type: Refer to question_type table in database
  "type": 1
}

### Add choice
// @name addChoice
POST  http://{{apphost}}:{{appport}}/api/edit/quiz/{{quiz_id}}/question/{{question_id}}/choice
Content-Type: application/json

{
  "text": "Choice 1",
  "is_correct": 0
}

###

@choice_id = {{addChoice.response.body.lastID}}

### Update choice
PUT  http://{{apphost}}:{{appport}}/api/edit/quiz/{{quiz_id}}/question/{{question_id}}/choice/{{choice_id}}
Content-Type: application/json

{
  "text": "Choice 1 v2",
  "is_correct": 0
}

###
