### Using: @ext:rest REST Client VSCode extension
@apphost = {{$dotenv APP_HOST}}
@appport = {{$dotenv APP_PORT}}

### DEBUG
GET http://{{apphost}}:{{appport}}/api/edit

### Add quiz
// @name addQuiz
POST http://{{apphost}}:{{appport}}/api/edit/quiz
Content-Type: application/json

{
  "title": "Quiz 2",
  "questions": 5
}

###

@quiz_id = {{addQuiz.response.body.lastID}}

### Update quiz
PUT http://{{apphost}}:{{appport}}/api/edit/quiz/{{quiz_id}}
Content-Type: application/json

{
  "title": "Quiz 1 v2",
  "questions": 9
}

### Publish quiz
PUT http://{{apphost}}:{{appport}}/api/edit/quiz/publish/{{quiz_id}}

###
