### Using: @ext:rest REST Client VSCode extension
@apphost = {{$dotenv APP_HOST}}
@appport = {{$dotenv APP_PORT}}

### DEBUG
GET http://{{apphost}}:{{appport}}/api/quiz/q0we98r7we90r87qwer09q8we7r

### Get quiz info
GET http://{{apphost}}:{{appport}}/api/quiz/q0we98r7we90r87qwer09q8we7r